## Numpy Array operations

In [1]:
import numpy as np

In [2]:
arr =np.arange(1,11)
print(arr[1:5])


[2 3 4 5]


In [8]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[1,2])

print("Entire row",arr[1])
print("Entire column",arr[:,2])

6
Entire row [4 5 6]
Entire column [3 6 9]


## Sorting

In [17]:
unsorted=np.array([8,5,9,1,7,3,6,4,8,2,9,5,11,89,42,10])
print(np.sort(unsorted))

arr_2d=np.array([[8,3,9],[2,1,7]])
print("\n",np.sort(arr_2d,axis=1))  # left to right

print("\n",np.sort(arr_2d,axis=0))  #top to bottom

[ 1  2  3  4  5  5  6  7  8  8  9  9 10 11 42 89]

 [[3 8 9]
 [1 2 7]]

 [[2 1 7]
 [8 3 9]]


## Filter

In [18]:
num=np.arange(12)
even=num[num%2==0]
print(even)

[ 0  2  4  6  8 10]


## Filter with mask

In [19]:
mask = num > 5
print(num[mask])

[ 6  7  8  9 10 11]


## Fancy indexing vs np.where()

In [22]:
indices=[0,2,5]
print(num[indices])

where_result=np.where(num>5)
print(num[where_result])

[0 2 5]
[ 6  7  8  9 10 11]


In [28]:
condition_array=np.where(num>5,num*2,num ) # num*2 is x and num is y
print(condition_array)

# explanation of above code

# if(num>5){
#    num* 2
# }else{
#    num
# }

cond_array=np.where(num>5,True,False )
print(cond_array)

[ 0  1  2  3  4  5 12 14 16 18 20 22]
[False False False False False False  True  True  True  True  True  True]


## Adding and Removing data

In [32]:
arr=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr+arr2)

print(np.concatenate((arr,arr2)))

[5 7 9]
[1 2 3 4 5 6]


### Array compatility

In [36]:
arr=np.array([1,2,3])
arr2=np.array([4,5,6,8])
arr3=np.array([7,8,9])

print("Compatibity shapes",arr.shape==arr2.shape)
print("Compatibity shapes",arr.shape==arr3.shape)

Compatibity shapes False
Compatibity shapes True


In [ ]:
original=np.array([[1,2],[3,4]])
new_row=np.array([8,9])

with_new_row=np.vstack((original,new_row))
print(with_new_row) #vstack add new row

new_col=np.array([[7],[48],[89]])
print("\n",np.hstack((with_new_row,new_col))) #hstack add new column  



[[1 2]
 [3 4]
 [8 9]]

 [[ 1  2  7]
 [ 3  4 48]
 [ 8  9 89]]


In [48]:
arr=np.array([1,2,3,4])
deleted=np.delete(arr,2)
print(deleted)

[1 2 4]
