##Shift + Enter to run the code


In [12]:
import numpy as np

In [13]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [14]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
c=np.arange(1,11)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
e=np.ones((3,3))
print(e)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
f=[1,2,3] ## python list
print(f*2)
g=np.array([1,2,3])
print(g*2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [19]:
full=np.full((4,3),6) ## to get matrix of constants
print(full)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


In [20]:
random=np.random.random((2,3))
print(random)

[[0.11876231 0.10238152 0.02257828]
 [0.89467025 0.97661939 0.93638919]]


##vector -> 1d array 

## matrix ->2d array 
tensor -> mutidimensional array

In [21]:
arr=np.array([[1,2],[3,4]])
print(arr.shape) ##order of matrix
print(arr.size)  ## total number of elements
print(arr.dtype)  ##datatype
print(arr.ndim)  ## dimension of matrix

(2, 2)
4
int64
2


In [28]:
arr=np.arange(12)
print(arr)

reshape=arr.reshape((4,3))
print("\n",reshape)

flat=reshape.flatten()
print("\n",flat)

#ravel (returns view , instead of copy)
ravel=reshape.ravel()
print("\n",ravel)

transpose = reshape.T
print("\n",transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
